#!/bin/bash
# ╭─────────────────────────────────────────────────────────────────────────────╮
# │ 🌱 BONSAI Mutt Account Setup Wizard                                         │
# │ Configure email accounts for mutt                                           │
# ╰─────────────────────────────────────────────────────────────────────────────╯

# BONSAI Colors
BONSAI_GREEN="\e[38;2;124;152;133m"
BONSAI_BLUE="\e[38;2;130;164;199m"
BONSAI_YELLOW="\e[38;2;199;168;130m"
BONSAI_RED="\e[38;2;199;130;137m"
BONSAI_TEXT="\e[38;2;230;232;235m"
BONSAI_MUTED="\e[38;2;139;146;165m"
RESET="\e[0m"

# Ensure cache directories exist (prevent cache errors)
mkdir -p ~/.cache/mutt/{headers,messages}
mkdir -p ~/.config/mutt/accounts

clear
echo -e "${BONSAI_GREEN}"
echo "╭─────────────────────────────────────────────────────────────────╮"
echo "│           🌱 BONSAI Mutt Account Setup                         │"
echo "│           Minimal • Purposeful • Beautiful                     │"
echo "╰─────────────────────────────────────────────────────────────────╯"
echo -e "${RESET}\n"

echo -e "${BONSAI_TEXT}Select email provider:${RESET}\n"
echo -e "  ${BONSAI_GREEN}[1]${RESET} Gmail"
echo -e "  ${BONSAI_GREEN}[2]${RESET} T-Online"
echo -e "  ${BONSAI_GREEN}[3]${RESET} Outlook/Hotmail"
echo -e "  ${BONSAI_GREEN}[4]${RESET} Yahoo Mail"
echo -e "  ${BONSAI_GREEN}[5]${RESET} Custom IMAP/SMTP"
echo ""

read -p "$(echo -e ${BONSAI_YELLOW}Choice [1-5]: ${RESET})" choice

echo ""
read -p "$(echo -e ${BONSAI_BLUE}Email address: ${RESET})" email
read -p "$(echo -e ${BONSAI_BLUE}Full name: ${RESET})" fullname
read -sp "$(echo -e ${BONSAI_BLUE}Password: ${RESET})" password
echo -e "\n"

# Check if pass is initialized
if ! pass ls &>/dev/null; then
    echo -e "${BONSAI_YELLOW}Initializing password store...${RESET}"
    gpg_key=$(gpg --list-secret-keys --keyid-format LONG 2>/dev/null | grep sec | head -1 | awk '{print $2}' | cut -d'/' -f2)
    if [ -z "$gpg_key" ]; then
        echo -e "${BONSAI_RED}No GPG key found. Creating one...${RESET}"
        gpg --batch --generate-key <<EOF
Key-Type: RSA
Key-Length: 2048
Name-Real: $fullname
Name-Email: $email
Expire-Date: 0
%no-protection
%commit
EOF
        gpg_key=$(gpg --list-secret-keys --keyid-format LONG | grep sec | head -1 | awk '{print $2}' | cut -d'/' -f2)
    fi
    pass init "$gpg_key"
fi

# Store password securely
echo "$password" | pass insert --echo "mutt/$email" &>/dev/null

# Create account configuration based on provider
config_file="$HOME/.config/mutt/accounts/$(echo $email | sed 's/@.*$//')"

case $choice in
    1) # Gmail
        cat > "$config_file" <<EOF
# Gmail Account - $email
# Generated by BONSAI Mutt Setup

set realname = "$fullname"
set from = "$email"
set imap_user = "$email"
set imap_pass = "\`pass mutt/$email\`"
set smtp_url = "smtps://${email}@smtp.gmail.com:465"
set smtp_pass = "\`pass mutt/$email\`"
set folder = "imaps://imap.gmail.com:993"
set spoolfile = "+INBOX"
set postponed = "+[Gmail]/Drafts"
set trash = "+[Gmail]/Trash"
set record = "+[Gmail]/Sent Mail"

# Gmail-specific settings
set imap_check_subscribed = yes
set imap_keepalive = 300
set mail_check = 120
set timeout = 300
set imap_passive = no
EOF
        echo -e "${BONSAI_GREEN}✓ Gmail account configured${RESET}"
        echo -e "${BONSAI_YELLOW}Note: You need to either:${RESET}"
        echo -e "${BONSAI_TEXT}  1. Enable 'Less secure app access' (not recommended)${RESET}"
        echo -e "${BONSAI_TEXT}  2. Generate an App Password (recommended):${RESET}"
        echo -e "${BONSAI_MUTED}     - Go to https://myaccount.google.com/security${RESET}"
        echo -e "${BONSAI_MUTED}     - Enable 2-factor authentication${RESET}"
        echo -e "${BONSAI_MUTED}     - Generate an App Password for Mail${RESET}"
        echo -e "${BONSAI_MUTED}     - Update the password with: pass edit mutt/$email${RESET}"
        ;;
        
    2) # T-Online
        cat > "$config_file" <<EOF
# T-Online Account - $email
# Generated by BONSAI Mutt Setup

set realname = "$fullname"
set from = "$email"
set imap_user = "$email"
set imap_pass = "\`pass mutt/$email\`"
set smtp_url = "smtps://${email}@securesmtp.t-online.de:465"
set smtp_pass = "\`pass mutt/$email\`"
set folder = "imaps://secureimap.t-online.de:993"
set spoolfile = "+INBOX"
set postponed = "+Entwürfe"
set trash = "+Papierkorb"
set record = "+Gesendet"

# T-Online specific settings
set imap_check_subscribed = yes
set imap_keepalive = 300
set mail_check = 120
EOF
        echo -e "${BONSAI_GREEN}✓ T-Online account configured${RESET}"
        ;;

    3) # Outlook/Hotmail
        cat > "$config_file" <<EOF
# Outlook/Hotmail Account - $email
# Generated by BONSAI Mutt Setup

set realname = "$fullname"
set from = "$email"
set imap_user = "$email"
set imap_pass = "\`pass mutt/$email\`"
set smtp_url = "smtp://${email}@smtp-mail.outlook.com:587"
set smtp_pass = "\`pass mutt/$email\`"
set smtp_authenticators = "login"
set folder = "imaps://outlook.office365.com:993"
set spoolfile = "+INBOX"
set postponed = "+Drafts"
set trash = "+Deleted"
set record = "+Sent"

# Outlook specific settings
set ssl_starttls = yes
set ssl_force_tls = yes
EOF
        echo -e "${BONSAI_GREEN}✓ Outlook/Hotmail account configured${RESET}"
        ;;

    4) # Yahoo
        cat > "$config_file" <<EOF
# Yahoo Mail Account - $email
# Generated by BONSAI Mutt Setup

set realname = "$fullname"
set from = "$email"
set imap_user = "$email"
set imap_pass = "\`pass mutt/$email\`"
set smtp_url = "smtps://${email}@smtp.mail.yahoo.com:465"
set smtp_pass = "\`pass mutt/$email\`"
set folder = "imaps://imap.mail.yahoo.com:993"
set spoolfile = "+INBOX"
set postponed = "+Drafts"
set trash = "+Trash"
set record = "+Sent"

# Yahoo specific settings
set imap_check_subscribed = yes
EOF
        echo -e "${BONSAI_GREEN}✓ Yahoo Mail account configured${RESET}"
        echo -e "${BONSAI_YELLOW}Note: You may need to generate an App Password${RESET}"
        ;;

    5) # Custom
        echo -e "${BONSAI_TEXT}Enter IMAP server details:${RESET}"
        read -p "$(echo -e ${BONSAI_BLUE}IMAP server \(e.g., imap.example.com\): ${RESET})" imap_server
        read -p "$(echo -e ${BONSAI_BLUE}IMAP port \(993 for SSL/TLS\): ${RESET})" imap_port
        echo -e "${BONSAI_TEXT}Enter SMTP server details:${RESET}"
        read -p "$(echo -e ${BONSAI_BLUE}SMTP server \(e.g., smtp.example.com\): ${RESET})" smtp_server
        read -p "$(echo -e ${BONSAI_BLUE}SMTP port \(465 for SSL, 587 for STARTTLS\): ${RESET})" smtp_port
        
        if [ "$smtp_port" = "587" ]; then
            smtp_proto="smtp"
        else
            smtp_proto="smtps"
        fi
        
        cat > "$config_file" <<EOF
# Custom IMAP/SMTP Account - $email
# Generated by BONSAI Mutt Setup

set realname = "$fullname"
set from = "$email"
set imap_user = "$email"
set imap_pass = "\`pass mutt/$email\`"
set smtp_url = "${smtp_proto}://${email}@${smtp_server}:${smtp_port}"
set smtp_pass = "\`pass mutt/$email\`"
set folder = "imaps://${imap_server}:${imap_port}"
set spoolfile = "+INBOX"
set postponed = "+Drafts"
set trash = "+Trash"
set record = "+Sent"

# Custom server settings
set ssl_starttls = yes
set ssl_force_tls = yes
EOF
        echo -e "${BONSAI_GREEN}✓ Custom account configured${RESET}"
        ;;
esac

# Add account to muttrc if not already there
account_name=$(basename "$config_file")
if ! grep -q "source.*$account_name" ~/.config/mutt/muttrc 2>/dev/null; then
    echo -e "\n# Account: $email" >> ~/.config/mutt/muttrc
    echo "source ~/.config/mutt/accounts/$account_name" >> ~/.config/mutt/muttrc
    echo "folder-hook $account_name/* source ~/.config/mutt/accounts/$account_name" >> ~/.config/mutt/muttrc
fi

echo -e "\n${BONSAI_GREEN}✓ Account added successfully!${RESET}"
echo -e "${BONSAI_TEXT}To switch accounts in mutt, press 'c' and select the folder.${RESET}"
echo -e "${BONSAI_MUTED}Configuration saved to: $config_file${RESET}"